name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js & yarn install if no cache exists
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Unit test
        run: yarn test:unit:ci

      - name: Component test
        run: yarn test:component:ci
