name: Test on main branch

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js & yarn install if no cache exists
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci
