name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn

      - name: Unit test
        run: yarn test:unit:ci

      - name: Component test
        run: yarn test:component:ci
